import { test, expect, type Page } from '@playwright/test'
import { car } from '../fixtures'
const cars = Array.from({ length: 25 }, (_, i) => car(String(i + 1), { displayName: `Toyota Mẫu ${String(i + 1).padStart(2, '0')}`, priceVndFrom: i === 24 ? null : 500000000 + i * 10000000, fuelType: 'Petrol', transmission: 'Automatic', marketStatusVn: 'official_current' }))
async function mockApi(page: Page, role: 'Guest' | 'Customer' | 'Admin' = 'Guest', authError = false) {
  let expired = false
  await page.route('**/api/**', async route => {
    const url = new URL(route.request().url())
    const path = url.pathname
    if (!path.startsWith('/api/')) return route.continue()
    const reply = (data: unknown, status = 200) => route.fulfill({ json: data, status })
    if (path.endsWith('/me')) return authError ? reply({ detail: 'Offline' }, 503) : role === 'Guest' || expired ? reply({}, 401) : reply({ id: 'customer-a', role, displayName: 'Khách thử nghiệm' })
    if (path.endsWith('/auth/csrf')) return reply({ token: 'test-token' })
    if (path.endsWith('/auth/login')) { role = 'Customer'; expired = false; return reply({ id: 'customer-a', role, displayName: 'Khách thử nghiệm' }) }
    if (path.endsWith('/auth/logout')) { expired = true; return route.fulfill({ status: 204 }) }
    if (path.endsWith('/my/profile')) return reply({ id: 'customer-a', displayName: 'Khách thử nghiệm', email: 'test@example.com', createdAt: '2026-10-01T00:00:00Z', version: 0 })
    if (path.endsWith('/assistant/sessions')) return reply([])
    if (path.endsWith('/orders')) return reply({ items: [], pageNumber: 1, pageSize: 20, totalCount: 0 })
    if (path === '/api/cars') return reply({ count: cars.length, items: cars })
    if (path === '/api/cars/compare') return reply({ items: cars.filter(c => url.searchParams.get('ids')?.split(',').includes(c.carId)), missingIds: [] })
    if (path.startsWith('/api/cars/')) return reply(cars.find(c => c.carId === path.split('/').at(-1)) || {}, cars.some(c => c.carId === path.split('/').at(-1)) ? 200 : 404)
    if (path === '/api/warranties') return reply({ items: [{ durationMonths: 36, distanceLimitKm: 100000, conditions: 'Xác nhận theo VIN.', sourceId: 'warranty-source' }] })
    if (path === '/api/dealers') return reply({ items: [{ dealerId: 1, name: 'Đại lý Toyota', supportedBrands: ['Toyota'], address: 'Hà Nội', city: 'Hà Nội', checkedAt: '2026-10-01' }] })
    if (path === '/api/chat') return reply({ answer: 'Mẫu xe phù hợp với nhu cầu.', contexts: [{ carId: '1', displayName: cars[0].displayName, presenceSourceId: 'source-presence' }] })
    return reply({ items: [], count: 0 })
  })
}
async function fits(page: Page) {
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth + 1)).toBe(true)
  await page.evaluate(() => window.scrollTo({ top: 0, behavior: 'instant' }))
}
test('catalogue, mobile menu, filters, comparison and detail', async ({ page }, info) => {
  const errors: string[] = []; page.on('pageerror', e => errors.push(e.message))
  await mockApi(page)
  await page.goto('/cars')
  await expect(page.locator('.car-card')).toHaveCount(12)
  if (page.viewportSize()!.width < 900) {
    const menu = page.getByRole('button', { name: 'Mở menu' }); await menu.click()
    await expect(page.getByRole('navigation', { name: 'Điều hướng chính' })).toBeVisible()
    await page.keyboard.press('Tab'); await page.keyboard.press('Escape')
    await expect(menu).toBeFocused()
    await expect(page.getByRole('navigation', { name: 'Điều hướng chính' })).toBeHidden()
    await page.getByRole('button', { name: 'Mở bộ lọc' }).click()
    const dialog = page.getByRole('dialog', { name: 'Bộ lọc xe' })
    const brand = dialog.getByRole('checkbox', { name: 'Toyota', exact: true })
    await brand.click(); await expect(brand).toBeChecked()
    await page.keyboard.press('Escape'); await expect(dialog).toBeHidden()
    await expect(page).toHaveURL(/brand=Toyota/)
  } else {
    const brand = page.locator('.catalog-desktop-filters').getByRole('checkbox', { name: 'Toyota', exact: true })
    await brand.click(); await expect(brand).toBeChecked()
  }
  await page.getByRole('button', { name: 'Trang sau' }).click(); await expect(page).toHaveURL(/page=2/)
  await page.reload(); await expect(page.getByText('Trang 2/3')).toBeVisible()
  await page.goBack(); await expect(page.getByText('Trang 1/3')).toBeVisible()
  for (let i = 0; i < 4; i++) await page.locator('.car-card').nth(i).getByRole('button', { name: '+ So sánh' }).click()
  await expect(page.getByRole('status').filter({ hasText: 'Chỉ có thể' })).toBeVisible()
  await fits(page)
  await page.screenshot({ path: info.outputPath('catalogue.png'), fullPage: true })
  await page.getByRole('link', { name: 'So sánh (3)' }).click()
  await expect(page.getByRole('table')).toBeVisible(); await fits(page)
  await page.screenshot({ path: info.outputPath('compare.png'), fullPage: true })
  await page.goto('/cars/1')
  await expect(page.getByRole('heading', { name: cars[0].displayName, exact: true })).toBeVisible()
  await expect(page.getByRole('link', { name: 'Nguồn chính sách bảo hành →' })).toHaveAttribute('href', '/sources/warranty-source')
  await fits(page); await page.screenshot({ path: info.outputPath('detail.png'), fullPage: true })
  await page.getByRole('link', { name: 'Hỏi về xe này' }).click()
  await expect(page.getByRole('textbox', { name: 'Câu hỏi' })).toHaveValue(`Hãy tư vấn cho tôi về xe ${cars[0].displayName}`)
  expect(errors).toEqual([])
})
test('guest chat retries, keyboard and refresh', async ({ page }, info) => {
  await mockApi(page); let tries = 0
  await page.route('**/api/chat', route => { tries++; return tries === 1 ? route.fulfill({ status: 503, json: {} }) : route.fulfill({ json: { answer: 'Câu trả lời đã phục hồi', contexts: [] } }) })
  await page.goto('/chat')
  const input = page.getByRole('textbox', { name: 'Câu hỏi' }); await input.fill('Tư vấn SUV')
  await input.press('Shift+Enter'); expect(tries).toBe(0)
  await input.press('Enter'); await expect(page.getByRole('button', { name: 'Gửi lại câu hỏi' })).toBeVisible()
  await page.getByRole('button', { name: 'Gửi lại câu hỏi' }).click()
  await expect(page.getByText('Câu trả lời đã phục hồi')).toBeVisible()
  await page.reload(); await expect(page.getByText('Câu trả lời đã phục hồi')).toBeVisible()
  await fits(page); await page.screenshot({ path: info.outputPath('guest-chat.png'), fullPage: true })
})
test('customer chat cache is cleared after logout', async ({ page }, info) => {
  await mockApi(page, 'Customer'); await page.goto('/chat')
  const input = page.getByRole('textbox', { name: 'Câu hỏi' }); await input.fill('Tư vấn SUV'); await input.press('Enter')
  await expect(page.getByText('Mẫu xe phù hợp với nhu cầu.')).toBeVisible()
  await page.reload(); await expect(page.getByText('Mẫu xe phù hợp với nhu cầu.')).toBeVisible()
  await fits(page); await page.screenshot({ path: info.outputPath('customer-chat.png'), fullPage: true })
  await page.goto('/account/profile'); await page.getByRole('button', { name: 'Đăng xuất', exact: true }).click()
  await expect(page).toHaveURL(/\/login/)
  await page.goto('/chat'); await expect(page.getByRole('heading', { name: 'Trợ lý AI của bạn.' })).toBeVisible()
  await expect(page.getByText('Mẫu xe phù hợp với nhu cầu.')).toHaveCount(0)
})
test('public remains usable during account outage and private route offers retry', async ({ page }) => {
  await mockApi(page, 'Guest', true); await page.goto('/cars')
  await expect(page.locator('.car-card')).toHaveCount(12)
  await page.goto('/account/profile'); await expect(page.getByText('Không kết nối được dịch vụ đơn hàng.')).toBeVisible()
  await expect(page.getByRole('button', { name: /Thử lại/ })).toBeVisible()
})
test('admin route remains guarded and visible', async ({ page }, info) => {
  await mockApi(page, 'Admin'); await page.goto('/cars'); await expect(page).toHaveURL(/\/admin\/orders/)
  await expect(page.getByRole('navigation', { name: 'Điều hướng quản trị' })).toBeVisible()
  await page.screenshot({ path: info.outputPath('admin.png'), fullPage: true })
  await expect(page.locator('.admin-header')).toBeVisible()
  expect(await page.locator('.admin-header').evaluate(header => header.getBoundingClientRect().bottom <= document.querySelector('main')!.getBoundingClientRect().top)).toBe(true)
})
test('login from guest order question returns to chat with the pending question', async ({ page }) => {
  await mockApi(page); await page.goto('/chat')
  await page.getByRole('textbox', { name: 'Câu hỏi' }).fill('Đơn hàng của tôi')
  await page.getByRole('button', { name: 'Gửi →' }).click()
  await expect(page.getByText('Bạn cần đăng nhập để tra cứu và xử lý đơn hàng của mình.')).toBeVisible()
  await page.getByRole('link', { name: 'Đăng nhập để tra cứu đơn hàng →' }).click()
  await page.getByLabel('Email', { exact: true }).fill('test@example.com')
  await page.getByLabel('Mật khẩu', { exact: true }).fill('test-password')
  await page.getByRole('button', { name: 'Đăng nhập', exact: true }).click()
  await expect(page).toHaveURL(/\/chat$/)
  await expect(page.getByRole('textbox', { name: 'Câu hỏi' })).toHaveValue('Đơn hàng của tôi')
})
